### ISSUE TITLE
List on fsharp.org/community/projects?

### ISSUE THREAD

**Issue by dsyme** [jmecosta/sonar-fsharp-plugin#1]
Hi @jmecosta - 

Great work on this!

You might want to list this at http://fsharp.org/community/projects, that will help people find it and know they can contribute to it

Cheers!
Don

**Comment by jmecosta** [comment]
hi @dsyme 

thanks for the feedback, will do, thanks.

Still trying to convince sonar folks to accept it sonar forge. :)
Cheers,
JC

**Comment by dsyme** [comment]
Hi @jmecosta - DO you know what it would take to get this accepted on sonar forge?

thanks
don

**Comment by jmecosta** [comment]
@dsyme no idea, last ive heard there was a email sent by sonar guys asking feedback to people at Microsoft regarding fsharp compiler service. I havent heard back.

in sum the problem seems related that the plugin heavily reuses fsharplint as its lint instead of implementing the same rules inside the plugin, which i dont agree totally. 

anyway i can ping again the people, the topic is here https://groups.google.com/forum/#!searchin/sonarqube/new$20fsharp/sonarqube/kKXYwku33UU/dQZdbSbbLlgJ however the main discussion went down the radar
