### ISSUE TITLE
several rules are showing as deprecated

### ISSUE THREAD

**Issue by jmecosta** [jmecosta/sonar-fsharp-plugin#57]
@milbrandt do u have the same?

![image](https://user-images.githubusercontent.com/1041352/59555201-97cb9700-8fb7-11e9-97c0-a2e75ad78cca.png)

**Comment by milbrandt** [comment]
Unfortunately yes, and all rules are marked as major in 1.0.6.122. 
In 1.0.6.110 there where already the same number of deprecated rules, but with information  as severity level.

Maybe there is also a predefined alternative for giving the severity string in each call of `activateRule`. Otherwise we should introduce an enumeration of strings for the severity levels.

![screenshot1-0-6-110](https://user-images.githubusercontent.com/26173245/59556738-0a447300-8fc8-11e9-9930-c0129b424eeb.png)

**Comment by milbrandt** [comment]
released 1.0.5 and even the old 1.0.3 (Oct 2018) have the same behavior as 1.0.6.110

**Comment by milbrandt** [comment]
`org.sonar.api.rule.Severity` contails al the supported severity values, see [Plugin API](cs.sonarsource.org/latest/apidocs/index.html?org/sonar/api/batch/sensor/Sensor.html)

**Comment by milbrandt** [comment]
In `org.sonar.plugins.fsharp.FSharpSonarRulesDefinition`, lines 191 ff.,  the rule names for several rules are set explicitly to _deprecated rule_. These rules were added on Feb 20, 2018 in commit 3a4847584ae9ae018ee6a8403e59d1b4886c9214

**Comment by jmecosta** [comment]
ok, so lets remove them since they have been deprecated for a while. i remenber this was done when there was a major refactoring in fsharplint

**Comment by milbrandt** [comment]
There are several rules in `FSharpSonarRulesDefinition` which aren't included `FSharpSonarWayProfile`. Have you deprecated them long ago?
I created a branch for some refactoring the above and observed now these additional rules like RulesNamingConventionsTypesError.

**Comment by jmecosta** [comment]
i think at least more than a year! anwyay, fharp lint will not produce those anymore so we should just remove them.

**Comment by milbrandt** [comment]
removed in v1.1.0
